#version: '3.9'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - early_dot_network # ğŸ’¡ ë„¤íŠ¸ì›Œí¬ ëª…ì‹œì  ì—°ê²°

  django:
    build: ./backend
    container_name: project_django
    env_file:
      - .env
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - fastapi
    networks:
      - early_dot_network # ğŸ’¡ ë„¤íŠ¸ì›Œí¬ ëª…ì‹œì  ì—°ê²°

  # ì•„ì§ ë¯¸ì‚¬ìš©ì´ì§€ë§Œ ë‚˜ì¤‘ì„ ìœ„í•´ ë¯¸ë¦¬ êµ¬ì¡°ë§Œ ë‘ 
  fastapi:
    build: ./model_api
    container_name: project_model_api
    env_file:
      - .env
    volumes:
      - ./model_api:/app
    ports:
      - "8001:8001"
    networks:
      - early_dot_network # ğŸ’¡ ë„¤íŠ¸ì›Œí¬ ëª…ì‹œì  ì—°ê²°
    # command: ["sleep", "infinity"]

  frontend:
    build: ./frontend
    container_name: project_frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - django
    networks:
      - early_dot_network # ğŸ’¡ ë„¤íŠ¸ì›Œí¬ ëª…ì‹œì  ì—°ê²°

volumes:
  db_data:

# ğŸ’¡ ëª…ì‹œì ì¸ ë„¤íŠ¸ì›Œí¬ ì •ì˜ ì„¹ì…˜ì„ ì¶”ê°€í•©ë‹ˆë‹¤.
networks:
  early_dot_network:
    driver: bridge # ê¸°ë³¸ bridge ë„¤íŠ¸ì›Œí¬ ì‚¬ìš©ì„ ëª…ì‹œ
