name: early_dot_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - aom=3.5.0=h7ea286d_0
  - blas=1.0=openblas
  - brotlicffi=1.0.9.2=py310h313beb8_1
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.34.5=h5505292_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cairo=1.18.4=h191e429_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=2.0.0=py310h3a083c1_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - dav1d=1.2.1=h80987f9_0
  - expat=2.7.1=h313beb8_0
  - ffmpeg=5.1.2=gpl_hf318d42_106
  - filelock=3.17.0=py310hca03da5_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h1383a14_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.13.3=h47d26ad_0
  - fribidi=1.0.10=h1a28f6b_0
  - gettext=0.25.1=h3dcc1bd_0
  - gettext-tools=0.25.1=h493aca8_0
  - giflib=5.2.2=h80987f9_0
  - gmp=6.3.0=h313beb8_0
  - gmpy2=2.2.1=py310h5c1b81f_0
  - gnutls=3.7.9=hd26332c_0
  - graphite2=1.3.14=hc377ac9_1
  - harfbuzz=6.0.0=hd7af201_1
  - hdf5=1.14.0=nompi_h6b85c65_102
  - icu=72.1=he12128b_0
  - jasper=2.0.33=hc3cd1e9_1
  - jinja2=3.1.6=py310hca03da5_0
  - jpeg=9f=h2f69dba_0
  - krb5=1.21.3=h237132a_0
  - lame=3.100=h1a8c8d9_1003
  - lcms2=2.15=h481adae_0
  - lerc=4.0.0=h313beb8_0
  - libaec=1.1.4=h51d1e36_0
  - libasprintf=0.25.1=h493aca8_0
  - libasprintf-devel=0.25.1=h493aca8_0
  - libavif=0.11.1=h9f83d30_2
  - libblas=3.9.0=1_h2ec9a88_netlib
  - libcblas=3.9.0=5_h880f123_netlib
  - libcurl=8.14.1=h73640d1_0
  - libcxx=21.1.3=hf598326_0
  - libdeflate=1.22=h80987f9_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.4.4=hca03da5_1
  - libgettextpo=0.25.1=h493aca8_0
  - libgettextpo-devel=0.25.1=h493aca8_0
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libglib=2.84.2=hdc2269c_0
  - libiconv=1.18=h23cfdf5_2
  - libidn2=2.3.8=ha90df94_1
  - libintl=0.25.1=h493aca8_0
  - libintl-devel=0.25.1=h493aca8_0
  - libjpeg-turbo=2.0.0=h1a28f6b_0
  - liblapack=3.9.0=5_h880f123_netlib
  - liblapacke=3.9.0=5_h880f123_netlib
  - liblzma=5.8.1=h39f12f2_2
  - liblzma-devel=5.8.1=h39f12f2_2
  - libnghttp2=1.67.0=hc438710_0
  - libopenblas=0.3.30=hf2bb037_0
  - libopencv=4.7.0=py310hb4a851b_1
  - libopus=1.5.2=h48c0fde_0
  - libpng=1.6.39=h80987f9_0
  - libprotobuf=3.21.12=ha614eb4_2
  - libsqlite=3.50.4=hf8de324_0
  - libssh2=1.11.1=h1590b86_0
  - libtasn1=4.20.0=hc919400_1
  - libtiff=4.5.1=hc9ead59_1
  - libunistring=0.9.10=h3422bc3_0
  - libvpx=1.11.0=hc470f4d_3
  - libwebp=1.2.4=h999c80f_1
  - libwebp-base=1.2.4=h1a8c8d9_0
  - libxcb=1.13=h9b22ae9_1004
  - libxml2=2.11.5=he3bdae6_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=14.0.6=hc6e5704_0
  - lz4-c=1.9.4=h313beb8_1
  - markupsafe=3.0.2=py310h80987f9_0
  - mpc=1.3.1=h80987f9_0
  - mpfr=4.2.1=h80987f9_0
  - mpmath=1.3.0=py310hca03da5_0
  - ncurses=6.5=hee39554_0
  - nettle=3.9.1=h40ed0f5_0
  - networkx=3.4.2=py310hca03da5_0
  - numpy=1.26.4=py310h901140f_1
  - numpy-base=1.26.4=py310hae06d03_1
  - opencv=4.7.0=py310hb6292c7_1
  - openh264=2.3.1=hb7217d7_2
  - openjpeg=2.5.0=hbc2ba62_2
  - openssl=3.5.4=h5503f6c_0
  - p11-kit=0.24.1=h29577a5_0
  - pcre2=10.42=hb066dcc_1
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h09dc60e_0
  - pthread-stubs=0.4=hd74edd7_1002
  - py-opencv=4.7.0=py310h69fb684_1
  - pycparser=2.23=py310hca03da5_0
  - pysocks=1.7.1=py310hca03da5_0
  - python=3.10.19=h14e4db3_1_cpython
  - python_abi=3.10=8_cp310
  - pytorch=2.5.1=py3.10_0
  - pyyaml=6.0.3=py310hf4fd40f_0
  - readline=8.3=h0b18652_0
  - requests=2.32.5=py310hca03da5_0
  - setuptools=80.9.0=py310hca03da5_0
  - sqlite=3.50.2=h79febb2_1
  - svt-av1=1.4.1=h7ea286d_0
  - sympy=1.14.0=py310hca03da5_0
  - tk=8.6.15=hcd8a7d5_0
  - torchaudio=2.5.1=py310_cpu
  - torchvision=0.20.1=py310_cpu
  - typing_extensions=4.15.0=py310hca03da5_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.5.0=py310hca03da5_0
  - wheel=0.45.1=py310hca03da5_0
  - x264=1!164.3095=h57fd34a_2
  - x265=3.5=hbc6ce65_3
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - xz=5.8.1=h9a6d368_2
  - xz-gpl-tools=5.8.1=h9a6d368_2
  - xz-tools=5.8.1=h39f12f2_2
  - yaml=0.2.5=h1a28f6b_0
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h817c040_0
  - pip:
      - annotated-types==0.7.0
      - anyio==4.11.0
      - asgiref==3.10.0
      - boto3==1.40.55
      - botocore==1.40.55
      - click==8.3.0
      - django==5.2.7
      - django-cors-headers==4.9.0
      - django-environ==0.12.0
      - djangorestframework==3.16.1
      - djangorestframework-simplejwt==5.5.1
      - exceptiongroup==1.3.0
      - fastapi==0.119.0
      - h11==0.16.0
      - httptools==0.7.1
      - idna==3.11
      - jmespath==1.0.1
      - mysqlclient==2.2.7
      - npm==0.1.1
      - optional-django==0.1.0
      - pillow==12.0.0
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pyjwt==2.10.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - s3transfer==0.14.0
      - six==1.17.0
      - sniffio==1.3.1
      - sqlparse==0.5.3
      - starlette==0.48.0
      - typing-inspection==0.4.2
      - uvicorn==0.37.0
      - uvloop==0.22.1
      - watchfiles==1.1.1
      - websockets==15.0.1
prefix: /opt/miniconda3/envs/early_dot_env
